//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabTaskLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int Id { get; set; }
        public System.DateTime Time { get; set; }
        public string Status { get; set; }
        public int Qty { get; set; }
        public int CreatedBy { get; set; }
        public int SId { get; set; }
    }
}
